### ISSUE TITLE
Smaller Window Mode / Resolution Selection

### ISSUE THREAD

**Issue by JaredBanyard** [projectM-visualizer/frontend-sdl2#2]
In order to use these visuals with streaming software or other tools, a small/non-full-screen windowed mode is required unless you run a 3rd/4th monitor. I have hacked this to work in the config file, but being able to switch through standard resolutions for window/full screen would be great (360p, 720p, 1080p, 1440p, 1600p, 2160p, native/widescreen).

Thanks so much!

**Comment by kblaschke** [comment]
Update: In the rewritten app, there now are a few more options to control the window size and fullscreen mode, but none yet to control the placement (monitor/coordinates) or window settings like borderless or always-on-top. Those will be added later though, current focus is on integrating a proper immediate-mode UI.

**Comment by kblaschke** [comment]
After a longer hiatus due to core library development (4.1 is finally out, yay!) I've been working again on the frontend, so here's a quick update on the progress.

My latest dev code has more options to control the window settings, including borderless mode and even adaptive vertical sync:
![projectMSDL Window/Rendering settings](https://github.com/projectM-visualizer/frontend-sdl2/assets/5038276/f3e278ca-92ed-4901-bc89-17142662ef12)

These settings are applied on startup and there's also a button to save the current window position to use it on the next start, which should be very convenient for streaming setups.

The "Reset" buttons simply reset each value to the factory default.

I'm going to merge the ImGui branch into master soon.

**Comment by kblaschke** [comment]
The new UI has been merged to master. While there's no dropdown list with resolutions, both window size and exclusive fullscreen resolution can be set to any desired values. If the sliders aren't precise enough, simply ctrl-/cmd-click on a slider to enter a specific value.
