### ISSUE TITLE
Tagged releases? Guidance for distro packagers?

### ISSUE THREAD

**Issue by colemickens** [projectM-visualizer/frontend-sdl2#28]
Hi.

Maybe I'm a bit early, but what is the release process for the split projectM?

We have 3.1.12 packaged in NixOS, presumably that is pre-split. What will the expectation be for the next release, or first release from the split repos?

Thanks!

**Comment by kblaschke** [comment]
Hi,

sorry for the late answer.

We currently have no firm release date, as there's still some work to be done on the libprojectM API, basically cleaning it up, removing unnecessary code and convert the built-in key handler into actual API methods for each feature currently only accessible via the key handler.

Next libprojectM release will be tagged with version 4.0, and the rewritten SDL frontend will use version 2.0. Having distinct versions will make it easier to release both projects individually, while having a (hopefully) stable API will make libprojectM backwards-compatible within each minor release version.

On the technical side, both parts are more or less feature-complete now for the release. The SDL frontend now has all the functionality the previous one had, specifically WASAPI capture support for Windows was added a few days ago. There are additional features planned like a reworked UI with actual dialogs to change settings and manage playlists, but those will be added in future releases. Same goes for libprojectM, there's still a bunch of internal bugs and missing features that need addressing, but these won't affect the external API in any way, which is why we decided to postpone this and concentrate on finishing the API.

I'll close this issue here as there's nothing do be fixed. Here are two ways you can check out to follow the progress or get in touch with use for further questions:

- Release 4.0 Kanban board: https://github.com/projectM-visualizer/projectm/projects/2
- Our Discord server, where I and the other devs are active: https://discord.gg/tpEuywB
