### ISSUE TITLE
[Feature Request] keyboard shortcut to put new random waveform at random coordinate

### ISSUE THREAD

**Issue by actionless** [projectM-visualizer/frontend-sdl2#31]
speaking of hotkey fixes and  random waveforms - are you planning to add also keyboard shortcuts for those?

using mouse is not an option because the mouse cursor will be visible on captured performance

_Originally posted by @actionless in https://github.com/projectM-visualizer/frontend-sdl2/issues/29#issuecomment-1140523305_

**Comment by kblaschke** [comment]
Sounds like a good feature to me. Probably won't make it into the initial release, but shortly after that.

**Comment by kblaschke** [comment]
The random waveform feature has been removed from the core library due to architectural changes making it hard to implement.

In the future, Milkdrop user sprites will be added, and possibly other features as well. Until then, I'll close this this issue as there's no longer a way to even add more waveforms.
