### ISSUE TITLE
Fails to start/hangs when running steam release.

### ISSUE THREAD

**Issue by brandorf** [projectM-visualizer/frontend-sdl2#42]
https://steamcommunity.com/app/1358800/discussions/0/3430075523250663749/

**Comment by kblaschke** [comment]
Please do not solely link to external sites when reporting bugs. Post all information here at GitHub and provide a link to the original discussion, if any, at the end just for reference.

Besides that, the issues in the Steam release are known and to our knowledge all fixed in the current development codebase. There's still some work to do before we officially release a new version, which will then also be uploaded on Steam.

Until then, you can use the development pre-releases I've built from my fork here:

https://github.com/kblaschke/frontend-sdl2/releases

These packages contain the rewritten frontend application from this repository which is more stable and has more configuration options. On Windows, the audio capture implementation is also greatly improved and now allows to switch between all available devices, while also supporting device hot(un)plugging.

I'm closing the issue for now, and will see if I can reach the Steam app admin to upload the pre-releases on Steam in a beta channel.
